export const GET_ALL_CHART_INFO = "GET_ALL_CHART_INFO";
export const PUSH_DEL_WHICH_ONE = "PUSH_DEL_WHICH_ONE";
export const GET_LINE_CHART_INFO = 'GET_LINE_CHART_INFO';
export const SET_EIDT_CHART_INFO = 'SET_EIDT_CHART_INFO';