export const MUTATE_FIRST_CHART_INFO = "MUTATE_FIRST_CHART_INFO";
export const MUTATE_DEL_WHICH_ONE = " MUTATE_DEL_WHICH_ONE";
export const MUTATE_LINE_CHART = 'MUTATE_LINE_CHART';
export const MUTATE_EDIT_CHART = 'MUTATE_EDIT_CHART';